### PR TITLE
Adds fancy-looking camouflage jumpsuit

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

Adds a fancy-looking camouflage jumpsuit which I intend to use for TerraGov outfits when/if it becomes a thing.

Otherwise, it's just a fancy-looking jumpsuit that has no natural means of spawning.

Sprite is from CM: https://github.com/MrStonedOne/cmhistory
https://github.com/MrStonedOne/cmhistory/commits/master/icons/obj/clothing/uniforms.dmi

## Why It's Good For The Game

It's fancy-looking.

image

## Did you test it?

Yah.

## Changelog

:cl:
tweak: Added fancy-looking jumpsuit. Currently unavailable outside of admin spawn.
/:cl:

### CODE REVIEW

**Comment by Ilysen** [comment]
> As far as I remember, the sprite itself is from CM.

I might just have strong opinions on this, but I'd really prefer if you could find the source on the sprite first. I try and be pretty stringent about unsourced assets.

**Comment by EgorDinamit** [comment]
> I might just have strong opinions on this, but I'd really prefer if you could find the source on the sprite first. I try and be pretty stringent about unsourced assets.

I got the sprite from TGMC codebase, but it is unused in-game and I couldn't find any PR that references it, so my only guess is it's from the older CM era.

**Review by Shadowtail117 — COMMENTED** [review]
[The blame of the .dmi file](https://github.com/MrStonedOne/cmhistory/commits/master/icons/obj/clothing/uniforms.dmi) is unattributable (without downloading each commit individually, which I am not about to do). Given its age I would say it's fine, but I would like a second opinion before approving the PR

**Comment by Cupax3** [comment]
> [The blame of the .dmi file](https://github.com/MrStonedOne/cmhistory/commits/master/icons/obj/clothing/uniforms.dmi) is unattributable (without downloading each commit individually, which I am not about to do). Given its age I would say it's fine, but I would like a second opinion before approving the PR

If the source is not directly identifiable and was lost to time, the criteria I'd measure it would be if it's a ubiquitous asset of the game - like the crystal - or if it's something only a single codebase holds. Depending on that we can likely infer the general disposition of the author.

**Review by Shadowtail117 — APPROVED** [review]

**Pull request merged**
