### PR TITLE
Update supermatter icons

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

Ports Baystation12/Baystation12/pull/30803

Also made the animation slower than it was in original PR.

## Why It's Good For The Game

It looks a bit better and some people already asked to port this specific PR.

## Did you test it?

No. It's a minor icon change.

## Changelog

:cl: Azlan
imageadd: Updated supermatter icons.
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
Could the old shard slots be kept, too?

**Comment by EgorDinamit** [comment]
> Could the old shard slots be kept, too?

What for?

**Comment by Shadowtail117** [comment]
Awaiting @Cupax3's response

**Review by Cupax3 — APPROVED** [review]
Barring no checks fail, LGTM

**Pull request merged**
