### PR TITLE
Fixes wiki manual books.

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

Removes parameters for links since they weren't working.

## Why It's Good For The Game

You can see the wiki from an IC source now.

## Did you test it?

Yes. Looks not so good, but it works.

## Changelog

:cl:
fix: Book manuals that lead to wiki now work again.
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
> [...] Looks not so good [...]

Any idea if we can improve that while we're at it?

**Comment by EgorDinamit** [comment]
> > [...] Looks not so good [...]
> 
> Any idea if we can improve that while we're at it?

I honestly have no idea. My only concern in this PR is to make it work instead of showing empty page.

**Comment by Shadowtail117** [comment]
The best option would likely be to either:
- Somehow make separate pages for each wiki page that are trimmed to be book-readable.
- Consult the wiki software itself to find what the actual links are for printable/no-link versions of a page.

Barring either of these discoveries this is the next best bet (and I believe is what most other servers use anyway).

**Comment by EgorDinamit** [comment]
Another solution could be making entirely new html file for each of those, just like lore and rules show up on the server right now.

**Comment by Cupax3** [comment]
> Somehow make separate pages for each wiki page that are trimmed to be book-readable.

Would require either authors doing that or a script. I doubt either of those would happen.

> Consult the wiki software itself to find what the actual links are for printable/no-link versions of a page.

Would require WikiMedia to be able to do that.

> Another solution could be making entirely new html file for each of those, just like lore and rules show up on the server right now.

That's feasible ngl but tedious as they would need to be re-made for every change.

**Comment by Shadowtail117** [comment]
Deferring to Cupax on this.

**Comment by Cupax3** [comment]
> Deferring to Cupax on this.

The author has not yet chosen an option.

**Comment by EgorDinamit** [comment]
I'd prefer to keep it like that for now. Any other option is either impossible or *very* tedious.

**Review by Shadowtail117 — APPROVED** [review]

**Pull request merged**
