### PR TITLE
Antagonist welcome Sounds

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About the Pull Request

more sounds to come eventually in separate PRs i swear

## Why It's Good For The Game

its a great reminder for players when they become antago

## Did you test it?

yup m8 i swear bro fr!

## Changelog

:cl:
rscadd: There are now several welcoming sounds for when you become an antagonist, it's a great reminder!
/:cl:

### CODE REVIEW

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
- Add it to preferences, so players can disable it at will.
- Remove/replace operative alert and fallback alert.
- For traitor alert might as well use the original, the low pitch doesn't help it to sound any better.
- Wizard alert is fine, but very difficult to notice; Could probably find another sound or do something about that one.

**Comment by EgorDinamit** [comment]
Oh, and move the sounds themselves from ambience to somewhere more appropriate.

**Comment by 77seven77seven** [comment]
> Oh, and move the sounds themselves from ambience to somewhere more appropriate.

I'm pretty sure the ambience folder prevents the game from adding any shitty effects to it, like the echo.

**Comment by 77seven77seven** [comment]
> * Add it to preferences, so players can disable it at will.
> * Remove/replace operative alert and fallback alert.
> * For traitor alert might as well use the original, the low pitch doesn't help it to sound any better.
> * Wizard alert is fine, but very difficult to notice; Could probably find another sound or do something about that one.

The fallback alert is for antagonists that aren't standard/admin only, theoretically it shouldn't show up in play. But having a fallback  is always a good idea in my opinion. But I'll try and make it sound better.
Nonetheless, I will try and fix the other issues.

**Comment by EgorDinamit** [comment]
> I'm pretty sure the ambience folder prevents the game from adding any shitty effects to it, like the echo.

Why would it ever work this way..?

**Comment by 77seven77seven** [comment]
> > I'm pretty sure the ambience folder prevents the game from adding any shitty effects to it, like the echo.
> 
> Why would it ever work this way..?

1. Ask the oldcoders.
2. generally ambience is not 'in-world' so it doesn't happen in the game space but rather for the player only, so the game doesn't apply echoes, or that's how it works i think

**Comment by EgorDinamit** [comment]
File's location has nothing to do with how it's played.

**Comment by 77seven77seven** [comment]
epic fixed

**Comment by goat-ster** [comment]
> epic fixed

Based

**Pull request merged**
