### PR TITLE
Lar Maria Map Revamp

### PR DESCRIPTION
**Pull request by Bam40002**
## About the Pull Request

This PR changes the Lar Maria map completely.

## Why It's Good For The Game

The old lar maria was really easy to do and the map itself wasnt really that great.

## Did you test it?

Yes (Though it might need a bit more testing and changes)

## Authorship

Map made by me.
Thanks to the original creator and others for the concept and enemies!

## Changelog

:cl:
- Remade the entire Lar Maria map.
- Buffed the enemies health slightly.
/:cl:

### CODE REVIEW

**Comment by Bam40002** [comment]
Well, I think thats it. The map is done and ready to be merged!

**Review by EgorDinamit — DISMISSED** [review]

**Comment by Bam40002** [comment]
Okay. Now its done!

**Comment by Bam40002** [comment]
Did I do that right? I dont know

**Comment by Bam40002** [comment]
Damn it i accidentally included something I should not have

**Comment by Bam40002** [comment]
I fucked it

Oh god what am I doing?

**Pull request closed without merging**
