### PR TITLE
Doors go beep

### PR DESCRIPTION
**Pull request by SkyCinnamon**
## About the Pull Request
Alt to #83 I didnt like it, I dont like the idea of the quiet sound so I increased it this time and I got rid of the old sound, yes I have tg sound nostalgia.  tg [pr](https://github.com/tgstation/tgstation/pull/16109) 

## Why It's Good For The Game
I find myself staring at a door wondering why it doesnt open until I realize I dont have access. I didnt find the previous sound appealing to be used for every door so I replaced it.

## Did you test it?
hell yeah brother

## Changelog

:cl: Sky, Cuboos
tweak: High security doors now make a different denied access sound
rscadd: Every door now makes a denied access sound 
/:cl:

### CODE REVIEW

**Comment by Ilysen** [comment]
Is tg's license different from ours at all?

**Comment by SkyCinnamon** [comment]
> Is tg's license different from ours at all?

Ive used stuff from tg before and im fairly certain its not

**Comment by Ilysen** [comment]
Go ahead and check that we're compatible just in case - I'd prefer to be extra safe regarding legal stuff.

**Comment by SkyCinnamon** [comment]
> Go ahead and check that we're compatible just in case - I'd prefer to be extra safe regarding legal stuff.

it is not no both agpl

**Comment by Ilysen** [comment]
Gotcha, thanks.

As for the PR itself, code looks like it's fine (since it'd be hard to mess up code changes that small, lol.) My one concern is that a volume of 100 would be too loud, when ideally the sound itself would be quiet, but it's possible the audio file itself is really quiet as it is. Deferring the overall content to popular opinion instead of my own.

**Comment by Cupax3** [comment]
This'll be a test-merge as 100 might be too loud on some players' machines. Better safe than sorry.

**Review by Ilysen — APPROVED** [review]
This has been testmerged for a bit and seems to work fine. 100% volume hasn't actually caused problems, and instead it seems to play at volume levels to be expected.

**Pull request merged**
