### PR TITLE
Diona have more clothes 

### PR DESCRIPTION
**Pull request by SkyCinnamon**
## About the Pull Request

This PR allows for Diona to have every clothes slot except shoes (requested by Jadyn). Also allows Diona to wear hard hats. spacesuits which were before directly blocked. 

## Why It's Good For The Game

Clothes for Diona allow for more possibilities within jobs. i.e gloves allow for Diona to wear insuls / latex gloves to prevent infections during surgery. Also more customizability and fun clothes allowed. 

## Did you test it?

Hell yeah brother!
image

## Changelog

:cl: Sky
tweak: Gloves, mask , second ear slot,  glasses are now available to Diona
tweak: Diona can now wear hard hats and space suits   
/:cl:

### CODE REVIEW

**Comment by Ilysen** [comment]
I have a few concerns about this.

From a fluff perspective: diona are gestalts of much smaller nymphs, and only have the rough shape of a humanoid, not a fine one. You can see this with how spiky their sprite is. As such, I'm not certain that any of their new slots (except the second ear slot) make much sense from a "why can we wear this" perspective - gloves especially would probably necessitate much more fine control of the shape than diona are capable of doing. Glasses are more forgivable, but I still find it unlikely that a gestalt could mirror the shape of a head enough to have both two eyes and a nose bridge positioned in the right way to wear glasses.

From a balance perspective: diona are much more durable than you probably realize. They feel no pain, have inbuilt space immunity, and can infinitely regenerate as long as they're in light, including lost limbs. Space suits provide a large amount of full armor, and also aren't ever needed for their actual purpose - that is, protecting from space - on a diona. I also don't believe that having a mask slot available provides any real benefit except "haha, the diona is smoking a cigarette, that is a funny meme." To my knowledge, they also do not have mouths, rendering it primarily a moot point except for jokes or fashion or whatever (might be wrong on that.)

Other than the example you cited in the OP - of diona being able to wear latex gloves during surgery - what benefit do these changes offer, compared to the narrative and mechanical discordance that they create?

**Comment by SkyCinnamon** [comment]
after discussion in lore general, over concerns of balance and lore some things will be changed, included but not limited to removal of the space suits idea, the rest is to be discussed later.

**Comment by Cupax3** [comment]
Please poke the Species Maintainer, I'm requesting they address concerns raised themselves, thank you.

**Comment by 0sj** [comment]
> Please poke the Species Maintainer, I'm requesting they address concerns raised themselves, thank you.

Already done

**Comment by Cupax3** [comment]
> > Please poke the Species Maintainer, I'm requesting they address concerns raised themselves, thank you.
> 
> Already done

Since no reply, yes, I'm asking you to address all the concerns here, please. Thank you.

**Comment by 0sj** [comment]
> > > Please poke the Species Maintainer, I'm requesting they address concerns raised themselves, thank you.
> > 
> > 
> > Already done
> 
> Since no reply, yes, I'm asking you to address all the concerns here, please. Thank you.

first, about balance: diona are not something you play to "win" at whatever you are doing, you also never fight others or anything similar as a diona, they are already very strong yet there has never been issues with dionas strength or resilience before, because in play it does not actually matter, they can already wear body armour and protective equipment anyway. 
Secondly, diona are not wholely made up of flat nymphs, they have various sections of their bodies dedicated to specific functions, eg radio transmission antenna, internal fusion systems, radiation harvesting bubbles and dead hard rocky flesh on their exteriors, with glasses for example, they could easily be propped up against some of their many small legs that can protrude from their form at will, with masks, they generally have straps that they could attach to pretty much any part of their head, with cigars, they would be purely cosmetic, individual nymphs have 'mouths' (holes) that can consume small items, they could easily hold a cigar somewhere on their face using these, they would not be able to inhale it however. 
Diona do not wear clothing for the benifits of the clothing, they wear it to seem more like those around them, they dont see naked humans on the torch, so why would we be naked?

**Comment by Cupax3** [comment]
Thank you.

**Comment by Ilysen** [comment]
After some discussion that'd happened in discord (prior to doing it here), I still think that letting diona have gloves is a bit silly - you even agreed. You offer plausible enough explanations for the rest, however, that I'm at least willing to give them a shot. Unfortunately, I don't believe there's a way to prevent the benefits of those glasses (mesons, etc) from appearing to the diona, which means that they're not purely cosmetic right now. I don't know whether or not that's enough of a problem that I'd block merge, but I encourage you to think about it.

**Comment by Ilysen** [comment]
Sky on discord: `post what to do on pr`

My current wishlist:
* Remove the gloves slot, since they'd be very pokey and not be able to actually wear the gloves.
* Prevent the space suit thing, for reasons already discussed.
* Either make sure doona can't wear things like HUDs and mesons by using species blacklists, or remove the goggles slot. I'm fine with either. I'm also fine letting 'em wear these things if you can figure out how to prevent them from conferring their benefits to a diona wearer - this is both because HUDs are very powerful, and because, as Jaydn said themselves, diona would be moreso propping the glasses up on their "head" instead of actually looking through the lenses.

While it's true that people don't play diona for mechanical benefit, I think that establishing some kind of standards and balance for species is important to do. This is why GAS are very weak to fire and flashes, Unathi require super heavy protein intake, and so on.

These aren't species that people play for their mechanical benefit, but I believe they nonetheless conform to a certain standard to keep them in the camp of either "close to human balance" or "very strong in some ways but weak in others." Even adherents have weaknesses in that they're super vulnerable to brute damage and their limbs will quickly shatter under any kind of sustained damage. Diona's big weaknesses are restriction of clothing and their slowdown, and I worry that removing a large aspect of this first part could skew this.

If you'd like to add anything to this or counter any of the points I've made, @0sj, please don't hesitate to do so! I respect your opinion on this, because you're a species maintainer.

**Comment by Cupax3** [comment]
@Samuuu3 Address balance concerns plox

**Comment by 0sj** [comment]
> 
> 
> Sky on discord: `post what to do on pr`
> 
> My current wishlist:
> 
>     * Remove the gloves slot, since they'd be very pokey and not be able to actually wear the gloves.
> 
>     * Prevent the space suit thing, for reasons already discussed.
> 
>     * Either make sure doona can't wear things like HUDs and mesons by using species blacklists, or remove the goggles slot. I'm fine with either. I'm also fine letting 'em wear these things if you can figure out how to prevent them from conferring their benefits to a diona wearer - this is both because HUDs are very powerful, and because, as Jaydn said themselves, diona would be moreso propping the glasses up on their "head" instead of actually looking through the lenses.
> 
> 
> While it's true that people don't play diona for mechanical benefit, I think that establishing some kind of standards and balance for species is important to do. This is why GAS are very weak to fire and flashes, Unathi require super heavy protein intake, and so on.
> 
> These aren't species that people play for their mechanical benefit, but I believe they nonetheless conform to a certain standard to keep them in the camp of either "close to human balance" or "very strong in some ways but weak in others." Even adherents have weaknesses in that they're super vulnerable to brute damage and their limbs will quickly shatter under any kind of sustained damage. Diona's big weaknesses are restriction of clothing and their slowdown, and I worry that removing a large aspect of this first part could skew this.
> 
> If you'd like to add anything to this or counter any of the points I've made, @0sj, please don't hesitate to do so! I respect your opinion on this, because you're a species maintainer.

im all for diona having goggles slot but if we cant get a system in place to disable the benefits they give, then im fine with leaving them out of the pr.
with the balance stuff, i would personally love for diona to have things they are super weak and die easily from, eg lipozine(i think that's what its called) and the way it kills diona by removing their hunger, or by making other things such as darkness more deadly, i personally think that diona surviving off flashlights and small lights is weird.
i would be interested in making it so they need something more like a floodlight array to survive when in dark environments, for example the torch loosing power, i may look into changing this in the near future but for now, i dont think giving diona more clothing options would seriously change the balance, right now they already have access to body armour ect ect. setting standards is a good idea however and i am in full support of giving diona weaknesses and a hard counter or two.

**Comment by SkyCinnamon** [comment]
me made mistake with git will reopen when i figure out what to do

**Pull request closed without merging**
