### PR TITLE
Blueriver nerf/tweak

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

Blueriver turfs no longer instantly kill everything that touches them. Instead, mobs will be given an opportunity to survive it given they aren't heavily damaged. It takes ~2 "hits" for a human mob to fall under required amount of health to be destroyed.
Also updated the bluespace clone code a bit so it can properly show lying mobs.

## Why It's Good For The Game

Removes yet another source of instant unexplained deaths. It is still hella dangerous but now accidentally walking into it doesn't round-end you, at least if you are 100% healthy.

## Did you test it?

Yes, everything works correctly.

## Authorship

Me

## Changelog

:cl:
tweak: Walking/Touching blueriver will no longer instantly kill you. Instead, you will be heavily damaged if you are healthy. If not - the old effect occurs.
/:cl:

### CODE REVIEW

**Review by Cupax3 — CHANGES_REQUESTED** [review]
I'm not opposed to making the bluespace river more forgiving, but I would like to have a "deep river" remain where the instant-death is still present. It's a dangerous ruin and should be high risk.

**Comment by EgorDinamit** [comment]
> I'm not opposed to making the bluespace river more forgiving, but I would like to have a "deep river" remain where the instant-death is still present. It's a dangerous ruin and should be high risk.

In **best** case scenario you would be able to step on 1 or 2 tiles of the river without dying, I don't see why we'd need a "deep river" when you won't ever reach it anyway.

**Comment by Cupax3** [comment]
> > I'm not opposed to making the bluespace river more forgiving, but I would like to have a "deep river" remain where the instant-death is still present. It's a dangerous ruin and should be high risk.
> 
> In **best** case scenario you would be able to step on 1 or 2 tiles of the river without dying, I don't see why we'd need a "deep river" when you won't ever reach it anyway.

In case someone throws a person in. Sneaky traitor.

**Comment by Shadowtail117** [comment]
I will agree with Cupax, the river needs to have some element of irreversible danger to it.

**Pull request merged**
