### PR TITLE
Shortwave radio resprite

### PR DESCRIPTION
**Pull request by SkyCinnamon**
## About the Pull Request

Resprites the current shortwave radio sprite with a modified version of the one from the [bee pr](https://github.com/BeeStation/BeeStation-Hornet/pull/5007)

orginal
image

my edit
image

## Why It's Good For The Game

the old sprite was fairly ugly, given a chance to modernize and make sprites look pretty why not take it. very minor change for a heavily used item.

## Did you test it?
Hell yeah!

## Changelog

:cl: ReneAngel, Sky
tweak: new shortwave radio sprite
/:cl:

### CODE REVIEW

**Review by Cupax3 — DISMISSED** [review]
Testmerge since weirdness with one icon

**Comment by Ilysen** [comment]
Indifferent to the sprite itself. However, could you move it more into the center of the 32x32 space? Icon diff bot tells me it's pretty weighted towards the bottom, but having centered sprites is better for visual consistency as well as placing things on tables.

**Comment by SkyCinnamon** [comment]
> Indifferent to the sprite itself. However, could you move it more into the center of the 32x32 space? Icon diff bot tells me it's pretty weighted towards the bottom, but having centered sprites is better for visual consistency as well as placing things on tables.

can do in a moment

**Review by Ilysen — APPROVED** [review]
wwzzzwzwwzwzwwzwzwzzwz

**Comment by Ilysen** [comment]
I've played a bit with this in testmerge, now, and it looks a bit worse in-game than I thought it would after seeing it here. The shading and color scheme conflicts a bit with baycode's use of dark floors, and it's a lot lower-visibility, whereas the existing shortwave sprite is a highly visible bright yellow.

image

Personally, I don't like the sprite change as a result, but I'm curious to see what other people think. I think that changing the outer shell to the same shade of yellow that the existing sprite uses might alleviate some of my concerns, and in general, making it brighter. On the whole, though, I'm kinda deferring to popular vote here.

**Review by Shadowtail117 — APPROVED** [review]
Does what it says on the tin, but I must agree with Ava that I don't think the sprite itself is as nice as the original radio sprite. Being a lot thinner/taller has some downsides to it.

**Comment by Ilysen** [comment]
I don't wanna be the person to let this sit in limbo, so I'll defer to Cups here. Shadow and I both have aesthetic concerns, but Sky's said in discord that they don't have the spriting chops necessary to make significant changes to the sprite. Close, or just merge it in despite the issues? @Cupax3

**Comment by Ilysen** [comment]
Closing by request of Sky, after Cups raised some concerns as well about the sprite and they decided not to continue the PR:

image

**Pull request closed without merging**
