### PR TITLE
Collectable hat goes green 

### PR DESCRIPTION
**Pull request by SkyCinnamon**
## About the Pull Request

Changed the collectable paper hat to be green. Updates description with a more snarky comment.
Had a green paper hat sprite on my desktop I made for a meme so I thought why not.

## Why It's Good For The Game

In the current state the collectable paperhat is underrated when compared to the other hats. for centuries the paper hat has been neglected by the collectable cat ear and beret enthusiasts. overall I believe this change will allow the paper hat army to assert dominance and undermine the cat ear nation. 

## Did you test it?

**Extensive** testing has been done over the past 2 hours  

## Changelog

:cl:
* Tweak: Collectable paper hat description
* Tweak: Collectable paper hat is now green
* Imageadd: new green hat sprite 
/:cl:

### CODE REVIEW

**Comment by 0sj** [comment]
could totally be a separate hat but good pr.

**Comment by Samuuu3** [comment]
Legendary description

**Review by Shadowtail117 — APPROVED** [review]
Does what it says on the tin

**Comment by Cupax3** [comment]
Squash please

**Comment by Cupax3** [comment]
Merge conflict with #42

**Comment by SkyCinnamon** [comment]
closing this due to intent to make a larger upcoming hat pr

**Pull request closed without merging**
