### PR TITLE
Updates more interfaces to use browser popups

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

Fax Machine and Newscaster now use browser popup.

## Why It's Good For The Game

It looks better.

image

image

## Did you test it?

Yep, that's how I took screenshots.

## Changelog

:cl:
tweak: Fax and Newscaster interfaces have been updated.
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
Has this been tested with moving away from the machines after the interface was opened?

**Comment by EgorDinamit** [comment]
Should work the same as browser output, aside from fancy-looking buttons and layout.

**Comment by Cupax3** [comment]
> Should work the same as browser output, aside from fancy-looking buttons and layout.

Please test locally.

**Review by Shadowtail117 — CHANGES_REQUESTED** [review]
image

As with the vote browser PR, please remove these extraneous brackets in any places.

**Comment by EgorDinamit** [comment]
@Shadowtail117 
Done and done.
image

@Cupax3 
Tested the windows and yes, they won't work when you are away from them, just as expected.

**Comment by EgorDinamit** [comment]
@Shadowtail117 
Done and done.
image

@Cupax3 
Tested the windows and yes, they won't work when you are away from them, just as expected.

**Review by Shadowtail117 — DISMISSED** [review]
image

Sorry, didn't catch this on first glance. The second "Fax Machine" is extraneous and should be removed.

**Comment by EgorDinamit** [comment]
@Shadowtail117 done.
Updated screenshots in the PR's body.

**Review by Shadowtail117 — APPROVED** [review]

**Pull request merged**
