### PR TITLE
Random sound edits

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

- Playsound proc can now be set to ignore the pressure in area.
- Field disperser fire sound when you are near it ignores pressure and overall sounds louder + has extra range.
- Limb dismemberment now plays sounds. Some of them were ported from /tg/station: tgstation/tgstation/pull/50558
- Bashing against a window is now louder to compensate for the fact that sound file itself is rather queit.

## Why It's Good For The Game

- Allows certain sounds to be heard regardless of being in a space/depressurized area.
- Funny sound for the funny canon.
- More sound hints as to what is happening around you.
- Knocking on the window was louder than bashing it. Live with this fact now.

## Did you test it?

Yes, everything works as expected with no runtimes.

## Changelog

:cl: EgorDinamit, Ryll/Shaps(/tg/) for sounds.
tweak: Field disperser now plays sound that ignores pressure. That means you will hear it regardless of it being in space.
tweak: Limb dismemberment now plays a sound.
tweak: Bashing against a window is now louder.
soundadd: Added sounds from /tg/ for limb dismemberment.
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
CL entry not complete.

**Comment by EgorDinamit** [comment]
> CL entry not complete.

Fixed.

**Comment by Shadowtail117** [comment]
The OFD change is a bit meh. Why should it be special when virtually all other sounds are diagetic?

**Comment by EgorDinamit** [comment]
> The OFD change is a bit meh. Why should it be special when virtually all other sounds are diagetic?

It's made because 99% of the time the OFD area is spaced and you hear no sound at all.
I'd imagine bigass canon makes a really loud sound and as such, I made this change.

**Review by Cupax3 — APPROVED** [review]

**Comment by Shadowtail117** [comment]
Screamtest has worked so far

**Pull request merged**
