### PR TITLE
Makes CI point out location of indentation errors

### PR DESCRIPTION
**Pull request by Shadowtail117**
## About the Pull Request

This PR in theory should print the file and line and all that jazz of where it sees an indentation error to prevent the current issue with #107.

as I don't know what .awk really is and I doubt this even works, this is a draft

## Why It's Good For The Game

CI qol

## Did you test it?

pain

## Changelog

N/A

### CODE REVIEW

**Comment by Shadowtail117** [comment]
chemistry change was intentional to see if CI would trip, but it was a different part of CI!!1!!11!!

**Comment by Shadowtail117** [comment]
Still not tested by virtue of not being able to, so let's hope that it works.

**Review by EgorDinamit — APPROVED** [review]
I have no idea how it works, but let's give it a try.

**Comment by Shadowtail117** [comment]
I still don't know what an .awk file even is.

**Pull request merged**
