### PR TITLE
Replaces old sprites, adds new ones.

### PR DESCRIPTION
**Pull request by Doctor-Derp**
## About the Pull Request
Replaces old sprites from our codebase with newer, better ones from other servers. 

image
(Diagram from [**Azlan's** PR](https://github.com/BeeStation/BeeStation-Hornet/pull/2461)!)
image
image
image
image
image
(Thanks to **PigeonVerde** for spriting all of these [beautiful medical kits](https://github.com/BeeStation/BeeStation-Hornet/pull/6716)!)

## Why It's Good For The Game
I feel if we replaced some of our older sprites with better ones, it would be refreshing. I take a break from here to play beestation, and I'm amazed at how sleek everything there is, while our codebase feels super clunky and old-- Better sprites would "rejuvenate" the codebase.

## Did you test it?
Yes.

## Authorship
**Azlan** - BeeStation/BeeStation-Hornet/pull/2461 For the Stock Parts respriting
**PigeonVerde** - https://github.com/BeeStation/BeeStation-Hornet/pull/6716 Sprited the medical kits!
Tau Ceti and Baystation - TauCetiStation/TauCetiClassic/pull/2989 / Baystation12/Baystation12/pull/19472 (For the carpets! (I can't read Russian, so check the PR!))

## Changelog

:cl:
imageadd - Adds carpets from Baystation and Tau Ceti.
imageadd - Replaces stock parts with Azlan's sprites. (Thanks!)
imageadd - Replaces medical kits with PigeonVerde's sprites. (Thanks!!)
imagedel - Overwrites old carpet, stockparts, and medical kit icons.
/:cl:

### CODE REVIEW

**Comment by Doctor-Derp** [comment]
As soon as I fix the problem with my editor, I'll update the PR. I'm also working on more sprites in the meantime!

**Comment by Doctor-Derp** [comment]
I ported from bee, bee ported from TG, and TG actually ported from Tau Cet. Tau Ceti then ported from BAYSTATION. So I guess it's all come full circle. I'll update my PR notes to reflect that.

**Comment by Doctor-Derp** [comment]
I've added a few more sprites and did some bugtesting, it's all ready to go.

**Review by EgorDinamit — DISMISSED** [review]
Looks good.

**Comment by Doctor-Derp** [comment]
I've fixed a minor bug where the brown carpet would merge with other carpets. I spoke with people on the development channel about this, and decided it wasn't a big issue-- but I decided I shouldn't just leave it. So, I fixed it. The downside was having to replace it on every. single. map. which contained brown carpets. Hence why my latest commit edits so many maps, just replacing the carpets.

**Review by EgorDinamit — APPROVED** [review]

**Pull request merged**
