### PR TITLE
Updating the AI core

### PR DESCRIPTION
**Pull request by Doctor-Derp**
## About the Pull Request

Fixes a few mapping mistakes, and generally makes the AI core and upload look better.
example
Reduced the amount of turrets in the AI core, and repositioned a few.
Changed up a LOT of the floor tiles.
Added a few fluff servers. They don't do anything besides look pretty and maybe open up RP opportunities.
Added Interior chamber blast doors.
example2
Removed a table from under the upload computer.
Changed some floor tiles.
Added a few wall-mounted flashers.
Added a high security door to the upload.

## Why It's Good For The Game

Fixes mapping mistakes and makes things look nice!

## Did you test it?

Nope-- Just minor rearranging and copying over. 

## Changelog

:cl:
maptweak: Updates the AI and Upload to look better and function better.
/:cl:

### CODE REVIEW

**Review by EgorDinamit — DISMISSED** [review]
Just a bunch of QOL mapping updates.
Looks fine to me.

**Comment by Cupax3** [comment]
While you're looking at the AI core, mind removing those turrets right in front of the blast doors? ... and the vault doors.

**Comment by Doctor-Derp** [comment]
Done-- this good?
example

**Comment by Cupax3** [comment]
There's two turrets in the entrance hallway blocking doors. Might as well remove those two - or relocate, if you find a better spot.

**Comment by Doctor-Derp** [comment]
Done. Removed those two.

**Review by EgorDinamit — DISMISSED** [review]
Looks fine to me.
If there are no other concerns - I'll get this merged.

**Comment by Doctor-Derp** [comment]
I believe I have successfully 'squashed'.

Or just broke something. It's probably okay.

**Review by Shadowtail117 — DISMISSED** [review]
CI looks good, map diffs look good.

**Comment by EgorDinamit** [comment]
I remember there were issues with blastdoor button IDs.
DM me once those are fixed and I'll merge the PR.

**Review by EgorDinamit — APPROVED** [review]
All is good. Merging.

**Pull request merged**
