### PR TITLE
Pizza shuttle

### PR DESCRIPTION
**Pull request by StiffRobot**
## About the Pull Request
A Major Bill's Pizza Delivery Shuttle can now be found as an awaysite on exoplanets

## Why It's Good For The Game
pizza

## Did you test it?
myes

## Changelog

:cl:
maptweak - Crashed pizza delivery shuttle
/:cl:

### CODE REVIEW

**Review by EgorDinamit — DISMISSED** [review]
Looks good to me.

**Comment by Cupax3** [comment]
Please squash

**Comment by Shadowtail117** [comment]
It depends on the Git client that you use. Feel free to ask in the pr-discussion channel for specific help; it's a straightforward process either way.

**Review by EgorDinamit — APPROVED** [review]
Commits squashed. Will merge if there are no other issues.

**Pull request merged**
