### PR TITLE
Extends running into things when confused

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

Partially ports Baystation12/Baystation12/pull/31110

## Why It's Good For The Game

More fun interactions.

## Did you test it?

Yes, works as expected.

## Changelog

:cl: Hubblenaut
tweak: When confused or being clumsy, you will now fall over railings, mineral baths, or slam into objects and walls when sprinting.
tweak: You can't get out of disposal bins or mineral baths when you're incapacitated.
bugfix: No longer phasing through walls using railings.
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
I see some harmful interactions there, like falling over railings. I'd rather get a couple of opinions on that.

**Comment by Shadowtail117** [comment]
Currently pending input from @Samuuu3

**Comment by Cupax3** [comment]
Missing @SkyCinnamon's verdict.

**Comment by SkyCinnamon** [comment]
> Missing @SkyCinnamon's verdict.

After thinking about it I personally want to see how much of an impact the disposals nerf has, I have concerns of people just tanking the damage for fast transport but could just be a concern I have that doesn't matter as much as I believe. As for everything else, its probably fine.

**Comment by Shadowtail117** [comment]
I share Sky's concern about the disposals damage nerf. A thread is available under pr-discussion for a more detailed parley on the matter.

**Comment by EgorDinamit** [comment]
All concerns were addressed. Should be good to go, I think.

**Review by Cupax3 — APPROVED** [review]
LGTM if the headmins are fine with it.

**Pull request merged**
