### PR TITLE
Actually readds Fleet jackets and polos

### PR DESCRIPTION
**Pull request by Drew156**
## About the Pull Request

Basically what it says in the title.  Fleet members can grab utility jackets and polo and pants uniforms from the vendors now, instead of them being admin spawn only.

## Why It's Good For The Game

Gives more variety to fleet players, also offers a few more storage slots using the jacket.

## Did you test it?
Yes, with Shuttle Pilot (E-7)

## Changelog

:cl: 
tweak: Adds Fleet Jackets and Polo and Pants back to the uniform vendors.
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
You need to put the changelog entry in a new line, á la
:cl:
example: bababooey
/:cl:

**Comment by Drew156** [comment]
fixed a typo that was causing a check to fail

**Review by Cupax3 — DISMISSED** [review]
LGTM

**Comment by Cupax3** [comment]
Now squash plox, ping on Discord for help

**Comment by Drew156** [comment]
Should be squashed

**Review by Shadowtail117 — APPROVED** [review]

**Review by Cupax3 — APPROVED** [review]
LGTM

**Pull request merged**
