### PR TITLE
Basic tgUI 4.3 Start

### PR DESCRIPTION
**Pull request by martinlyra**
## About the Pull Request

This is a proposal PR to implement the necessary basics of tgUI to the codebase. This is not a complete makeover of entire the UI system or an instant change that will bin nanoUI in no time. Experience has taught me one thing. Doing it one-man and single-handedly to an older Baycode codebase took me *nearly one year*. I recommend to start small, and eventually the tgUI takes over and nanoUI becomes a thing of the past.

With one important thing:
- All UI-related `STATUS_X` have been renamned to `UI_X` to stay consistent with the more widely accepted standard for UI stuff.

Draft PR because some more work needs to be done, as it is not yet integrated. For now I'll just start with converting those three, - if possible - from nanoUI to tgUI:
- APC
- Air Alarm
- SMES

Anymore pose the risk of holding this project and go stale. Plus we won't lose too much work or time gone into this if this gets rejected for a reason or other.

It also comes with some documentation on how to use it, and how to convert the old UI API to tgUI. It does not cover everything, but the important basics. They can be found in `tgui/docs`

## Why It's Good For The Game

nanoUI bad, tgUI good

nanoUI has the advantage of being simple. But it is also so far a liability to the performance in its current state. The features it offers are rather shallow and falls flat, all it just do is provide you an UI. And that is it.

tgUI is comparatively advanced and requires an infrastructure to it. But thankfully there are already one that can be easily ported and put to use. It is an implementation of React.JS, minified to easily distributable bundle files with webpack. Being even more full-ledged JavaScript, it is much more powerful and can handle data-processing on the client side rather than the server.

With that said. This lays out the groundwork allowing a transition from nanoUI to tgUI.

## Did you test it?

This includes an test-case added to the CI to make sure that the tgUI is both consistent and can be compiled without errors. I will let the CI handle it. Ah by the way, it also includes VSCode settings that allows the codebase to be launched from the VSCode, and the tgUI will be always be refreshened and rebuilt whenever needed.

So far it is stamped with `Works on My Machine` stamp.

## Changelog

:cl:
rscadd: Added tgUI 4.3
/:cl:

### CODE REVIEW

**Comment by Ilysen** [comment]
No qualms with the PR itself (haven't had time to review it + I agree very much with it) but I *do* have to ask you to change the "why it's good for the game" bit to something more substantial, even if it's just a sentence or two. Even just some advantages it has over nano would be fine.

**Comment by Shadowtail117** [comment]
You said you tested the change by converting a few UIs, is it possible to get before/after screenshots, if applicable?

**Comment by Cupax3** [comment]
@martinlyra Hellou, has there been an update/private progress or is this stale?

**Comment by martinlyra** [comment]
Sadly. It is stale. The circumstances I am in today are different than I was in when I opened this PR.

**Pull request closed without merging**
