### PR TITLE
Access for pilots / explorers

### PR DESCRIPTION
**Pull request by SkyCinnamon**
## About the Pull Request
allows for explorers to fly the Charon and pilots to have maint access when explorers do

## Why It's Good For The Game
Not sure why pilots couldnt have maint before when explorers could. also explorers being able to fly the Charon solves the issue of everyone being sad when there is no shuttle pilot or for lowpop

## Did you test it?
hell yeah!

## Changelog

:cl: Sky
tweak: Explorers can fly the Charon
tweak: shuttle pilots have maintenance access
/:cl:

### CODE REVIEW

**Comment by Ilysen** [comment]
I could foresee possible issues with explorers trying to take the helm of the Charon themselves, as they are wont to do. I'm torn on how I feel about that in particular. No objection to the pilot stuff, though. If we go for the explorer thing, make sure they also have cockpit access (or don't, I'm not a cop.)

I also learned last night that prospectors can access the Charon's cockpit, but they can't actually pilot the helm. While you're in the neighborhood, do you feel like that might be worth changing in either direction (i.e. either letting them move the ship or removing their helm access)? It might help with the possible weirdness there.

**Comment by Shadowtail117** [comment]
> I could foresee possible issues with explorers trying to take the helm of the Charon themselves, as they are wont to do. I'm torn on how I feel about that in particular. No objection to the pilot stuff, though. If we go for the explorer thing, make sure they also have cockpit access (or don't, I'm not a cop.)

This was brought up on the Discord, the general justification being that when there isn't a shuttle pilot, explorers are pretty much forced to use the GUP or not go out at all. (Personally, I prefer such a scenario over them having access and bypassing a shuttle pilot entirely, but it is open to debate.)

**Comment by Ilysen** [comment]
That's valid. I'm still curious about Sky's take on the bit about prospectors, but otherwise I'm willing to give the explorer thing a pass and see how it plays out.

**Comment by SkyCinnamon** [comment]
> That's valid. I'm still curious about Sky's take on the bit about prospectors, but otherwise I'm willing to give the explorer thing a pass and see how it plays out.

in my eyes prospectors are generally not the ones leading away missions. Generally speaking anyways they are the primary users of the gup and I believe them having ability to fly the charon will end in more use cases of them taking the charon to go mining or do prospector things as opposed to the intention of exploration missions. I see prospectors more in line with supply rather than exploration and their permissions of only having the helm but not access reflects this. I do not mind either way though if you wish me to change it I can

**Review by Ilysen — APPROVED** [review]
All your points are valid. I'm fine with this as-is.

**Review by Shadowtail117 — COMMENTED** [review]
My primary issue is the apparent obsoletion of shuttle pilots this threatens to create if an explorer decides "they're taking too long" or "I don't like them" and blasts off without them. Especially on low pop where it is more difficult to enforce someone breaking IC law, I think it's best to prevent such a situation from being able to be created. @Cupax3 can I ask for your legendary input?

**Comment by Cupax3** [comment]
> @Cupax3 can I ask for your legendary input?

For anybody stumbling on this who didn't follow the Discord discussion - due to valid concerns on the impact of this change for the role of Shuttle Pilot and its necessarity, this will be a test merge until such time that a informed decision, with the changed dynamic for Shuttle Pilot in mind, can be made.

**Comment by Cupax3** [comment]
In the interest of cleaning PRs, I'll merge this. May the future people know that this can be reverted once it comes upon the day that explorers and shuttle pilots are separated again.

**Pull request merged**
