### PR TITLE
Airlocks open&close faster

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

Airlocks animation time is halved, so is the time it takes for them to open/close "code-wise".
To do it I also added a variable to the doors so subtypes can have whatever opening/closing time they need.

## Why It's Good For The Game

Airlocks were disgustingly slow, in my opinion. This makes going through several airlocks less annoying.

## Did you test it?

I did, looks pretty good.

## Changelog

:cl:
tweak: Airlocks open and close faster.
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
I'm... not too sure on this one. Standby while I think about it.

**Comment by Shadowtail117** [comment]
I second Cupa's apprehension on this PR, it seems largely unnecessary.

**Comment by EgorDinamit** [comment]
Might want to do a test-merge to gather opinions from players.

**Comment by EgorDinamit** [comment]
This change is generally enjoyed by players. Should be merged, eventually.

**Review by Cupax3 — APPROVED** [review]
After thinking about it a bit more, this shouldn't have that much of an impact.
Approved on the note that it might get reverted if it turns out this disrupts the flow with more people in-game.

**Comment by Shadowtail117** [comment]
Tentatively merging then

**Pull request merged**
