### PR TITLE
Adds Mr. X

### PR DESCRIPTION
**Pull request by SkyCinnamon**
## About the Pull Request
adds an admin spawned monster with the sole intent on giving it to people. sound credit is a bass boosted version of https://freesound.org/people/Nox_Sound/sounds/530588/
sprite is originally from https://monophy.com/gifs/pixelart-sprite-mrx-eGsADFu1SgaWxJqpVp afaik.
keep in mind the bite sound is meant to be a place holder.

## Why It's Good For The Game
adds a fun admin spawn tool for when things are getting **heated**

## Did you test it?
Hell yeah brother! - alot of testing should work  _fingers crossed_

## Changelog

:cl: Sky
rscadd: Mr. X included with footsteps and their own natural weapon
/:cl:

### CODE REVIEW

**Comment by SkyCinnamon** [comment]
i did not touch the maps

**Review by Ilysen — CHANGES_REQUESTED** [review]
This is a very hard sell for me. We are an HRP server, and a line/boundary needs to be drawn for what features can go in. A few code problems here aside, I believe this PR falls well past the boundary of features that are not acceptable in a serious environment, and in its current state I do not believe it has a place here.

What benefit does this offer to the codebase and to the players as a whole? What's done here that can't be done by varediting an existing mob? This feels like it's just an overpowered admin-spawn mob with an unsourceable sprite that exists solely as a meme, and nothing else.

**Comment by SkyCinnamon** [comment]
> This is a very hard sell for me. We are an HRP server, and a line/boundary needs to be drawn for what features can go in. A few code problems here aside, I believe this PR falls well past the boundary of features that are not acceptable in a serious environment, and in its current state I do not believe it has a place here.
> 
> What benefit does this offer to the codebase and to the players as a whole? What's done here that can't be done by varediting an existing mob? This feels like it's just an overpowered admin-spawn mob with an unsourceable sprite that exists solely as a meme, and nothing else.

overall this adds multiple things impossible via var editing such as footsteps and ability to turn left and right. Its only an admin spawn so i didnt think it matters whether it was OP as theyd have var edits anyways. I dont mind changing base values if its really an issue.

**Comment by 0sj** [comment]
> 
> 
> This is a very hard sell for me. We are an HRP server, and a line/boundary needs to be drawn for what features can go in. A few code problems here aside, I believe this PR falls well past the boundary of features that are not acceptable in a serious environment, and in its current state I do not believe it has a place here.
> 
> What benefit does this offer to the codebase and to the players as a whole? What's done here that can't be done by varediting an existing mob? This feels like it's just an overpowered admin-spawn mob with an unsourceable sprite that exists solely as a meme, and nothing else.

i get that its not an hrp thing BUT it is admin only, fun events and comic relief items are always nice but only when admin spawned only, i dont think it would have any negative impact personally

**Comment by Ilysen** [comment]
I don't disagree that comic relief isn't inherently bad, but implementing it in this kind of form comes with several problems of its own, the least of which is that it erodes precedent for what can and should be added to the game's code. As a maintainer of the codebase, one of my responsibilities is quality control for what goes into the game, and I don't believe this matches the standards we set both for setting/tone consistency as well as for actual code quality. The code quality issues are things I'm always happy to help resolve, but the other issues here are packaged with the feature conceptually.

An extension was recently added that allows atoms to play a sound when they're moved - `/datum/extension/play_sound_on_moved` - that can be applied via proccall to fill the purpose of the footsteps, and all of the other logic, including sprites, health, atmos, and damage, can be replicated via VV. Hell, I could even show you how if you want.

We could also add ERP mechanics and have them admin-only, or add a language that consists of slur words and have that be admin-only, but that doesn't mean they'd be harmless. Additions to the code *matter*, even if they require button-pressing to happen, because it makes pressing those buttons to break character and atmosphere (sometimes in a round where people are trying to play seriously) not only much easier, but implicitly encouraged by the game itself because they already exist in convenient prefab form - after all, if it's good enough for the coders to approve and merge, then that typically means it's something that the coders would, ideally, support being used inside the game.

I can't deny that this would have no impact on the average player except when spawned, but like I mentioned earlier, I have to decide what goes into the codebase and why. I just can't see a tangible benefit that this offers when other alternatives already exist, because this PR would probably be the single most atmosphere-breaking thing in the code if it was merged. I don't like 
flexing my power like this, but at risk of being a spoil-sport, I'm calling this a no-go.

**Pull request closed without merging**
