### PR TITLE
Remove bashing windows and walls on help intent

### PR DESCRIPTION
**Pull request by Shadowtail117**
## About the Pull Request

If you are on help intent you will not longer bash walls or windows with whatever you're holding.

## Why It's Good For The Game

People who click to change what direction they are facing no longer have to deal with accidentally slamming their beverage into the wall at full speed.

## Did you test it?

Yes

## Changelog

:cl:
tweak: If you are on help intent, you will no longer attack walls or windows by clicking on them.
/:cl:

### CODE REVIEW

**Review by EgorDinamit — COMMENTED** [review]
This PR will be made obsolete when #260 is merged.
I will bring over those changes to it instead, if you think it is such a crucial feature, but aside from misclicking with a very dangerous weapon - I don't see why it would be needed.

**Comment by Shadowtail117** [comment]
Randomly hitting the medical reception's window/wall with a scalpel because you misclicked a button or just wanted to turn around without using the keyboard can upset the immersion of the game. It harms no one and does a lot to keep things believable.

**Comment by EgorDinamit** [comment]
Then I will add it to health standardization PR.

**Comment by Shadowtail117** [comment]
Will be closed when #260 is merged.

**Pull request closed without merging**
