### PR TITLE
Add config for sleep_offline

### PR DESCRIPTION
**Pull request by Shadowtail117**
## About the Pull Request

Adds a config option, `SLEEP_OFFLINE_AFTER_INIT` to the example config, disabled by default. If enabled, `world.sleep_offline` will be set to true once the MC finishes initializing, meaning that if there are zero players, the server will pause processing.

## Why It's Good For The Game

17 hour rounds bad.

## Did you test it?

I used breakpoints to determine if the appropriate statements were executed, which they were, but I have **not** actually tested leaving the server and joining back since VSC doesn't support that.

## Changelog

:cl:
admin: Added a config setting for world.sleep_offline.
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
I'll say off the bat that it'll be a continuous test merge due to the fact that this might break stuff, as sleep mode on literally any piece of software is prone to do, and that this is a feature that will likely become less and less needed as pop increases.
This is prone to change of circumstance or it working so exceptionally well that nothing breaks and a full merge will cause no issues for us and/or less-experienced downstreams.

**Comment by Shadowtail117** [comment]
My only major concern is unit tests, as the old code specifically budgeted for making sure this is disabled for them. I'm not sure if the unit test machine uses a special config -- if it's the default/no config then there won't be any issues since this is disabled by default.

As for potential hiccups with un-sleeping and stuff, that's beyond my capability to test. But this is an intrinsic part of BYOND so I would imagine it's relatively stable.

**Comment by Cupax3** [comment]
Even in the face of probably sounding facetious, sleep mode is a "feature" on other software, too. Doesn't mean it works well. BYOND itself suffers from a memory leak that is softlocking Windows if the OS sleeps for too long.

**Review by Cupax3 — APPROVED** [review]
Disregard previous, I thought another sleep mode was in question. The one already in is, well, already in. Should be good to merge soon.

**Review by Ilysen — CHANGES_REQUESTED** [review]
This might have the potential to break tests, now that the `#if UNIT_TEST` define isn't there. I think that there should be code in place to make sure that sleep mode never turns on if the define is there. You could probably keep the define, and then put the new config-checking code in the `#else` def. If cups wanted to overrule me on this, though, I won't stop 'em.

**Comment by Cupax3** [comment]
> This might have the potential to break tests, now that the `#if UNIT_TEST` define isn't there. I think that there should be code in place to make sure that sleep mode never turns on if the define is there. You could probably keep the define, and then put the new config-checking code in the `#else` def. If cups wanted to overrule me on this, though, I won't stop 'em.

Since the default is `false`, it should not be an issue. Having the ifdef present just in case wouldn't hurt though, aye.

**Comment by Shadowtail117** [comment]
As I said before, I assume the tests use the default config. This defaults to off, so it should not be an issue. Bringing in a define would unnecessarily complicate it.

**Comment by Cupax3** [comment]
I'll tentatively merge this - if checks start breaking without the if, expect it to be reverted.

**Pull request merged**
