### PR TITLE
Gas wear hat

### PR DESCRIPTION
**Pull request by SkyCinnamon**
## About the Pull Request

Allows GAS to wear softcaps. original idea from this bay [pr ](https://github.com/Baystation12/Baystation12/pull/30885)

## Why It's Good For The Game

Over the ions GAS have had but one question. Why? why must we suffer in the face of adversity and not be allowed to wear a simple thing such as a hat! If man has hands shall he have the right to wear hats? the answer is yes. some day they will evolve into superior beings, capable of wearing multiple different hats. For now however this is one hurdle GAS kind must face for if one does not have hats what is the purpose of life. 

## Did you test it?

Hell yeah brother!
image

## Changelog

:cl:Viimas21
* rscadd: GAS can now wear soft hats 
/:cl:

### CODE REVIEW

**Comment by SkyCinnamon** [comment]
grug made same mistake original pr did should be gaming now

**Comment by Cupax3** [comment]
Squash please

**Comment by Cupax3** [comment]
@Samuuu3 Species Maintainer goes lore reviewwwwww

**Review by Samuuu3 — APPROVED** [review]
Why not

**Pull request merged**
