### PR TITLE
Syringe resprite

### PR DESCRIPTION
**Pull request by SkyCinnamon**
## About the Pull Request
Resprites every type of syringe complete with the different fill amounts. Sprites except the broken one done by Retlaw from [here](https://github.com/shiptest-ss13/Shiptest/pull/194) - also changes the draw / inject icon with ones made by retlaw 
image

## Why It's Good For The Game
Current syringe sprites are very out dated and in my opinion do not look nice, they also have the issue of sometimes being impossible to click due to how small they can be.

## Did you test it?
hell yeah brother! 
image

## Changelog

:cl: Sky, Retlaw
tweak: New resprites of bluespace, normal and noreaction syringes
tweak: different reagent fillings in order to accommodate the new syringes
tweak: new inject and draw icons for syringes
/:cl:

### CODE REVIEW

**Comment by SkyCinnamon** [comment]
shortened tip and centered as requested on discord

**Comment by rye-rice** [comment]
😕

**Comment by Shadowtail117** [comment]
Not the greatest fan of how the syringes look. Their sprites are practically as big as a person and twice as big as the bottle next to them.

Making the container part thinner and shorter would probably help.

**Comment by SkyCinnamon** [comment]
> Not the greatest fan of how the syringes look. Their sprites are practically as big as a person and twice as big as the bottle next to them.
> 
> Making the container part thinner and shorter would probably help.

has been partly addressed with a shorter tip, not reflected in image

**Comment by rye-rice** [comment]
hey um, not to be a asshole but could you not use them? i know the agpl and such, but still.

**Comment by Ilysen** [comment]
It's allowed under the terms of the license, but generally we like to comply with the wishes of the people that made the sprite. In the interest of being respectful and generally cultivating a healthy community, I'm going to close this for now in accordance with retlaw requesting their sprites not be used. If you'd like to see about using these regardless, @SkyCinnamon, I'd page Cupax on discord, describe the situation, and ask for their thoughts.

**Comment by Shadowtail117** [comment]
> hey um, not to be a asshole but could you not use them? i know the agpl and such, but still.

Apologies, I had assumed your permission was given beforehand. Closing this PR for you, sorry about that.

**Comment by Shadowtail117** [comment]
that moment when we post at the same time...

**Comment by Shadowtail117** [comment]
image

Original spriter has given permission to use these sprites, re-opening on Sky's request.

**Comment by Cupax3** [comment]
Seeing as the original author is fine with the porting, could you squash this for a test merge?

**Comment by rye-rice** [comment]
I will say again here, I dont think these fit the bay artstyle, the old inject and draw icons were better as well

**Comment by SkyCinnamon** [comment]
pr updated to include inject / draw icons I forgot to port from the original pr, changelog has been updated

**Review by Cupax3 — APPROVED** [review]
The PR itself looks fine, the content is under the same scrutiny as #119 for me. This might get reverted; for now, approved.

**Pull request merged**
