### PR TITLE
Adds discord invite button to the interface

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

Replaces "Lore" button with "Discord" button on the interface.
"Lore button" is now an OOC verb, accessible all the time.

## Why It's Good For The Game

Lore shouldn't occupy space on the main interface. Having Discord invite here is much more useful since new players won't have to search for the link on the hub description or ask other players for it in the OOC.

## Did you test it?

Not yet.

## Changelog

:cl:
tweak: Added Discord invite button to the interface.
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
Apart from this failing checks, do you have an alternative way for players to reach lore information?

**Comment by EgorDinamit** [comment]
> Apart from this failing checks, do you have an alternative way for players to reach lore information?

We can always put it on the OOC verbs AND lobby, just like TGMC does.

**Comment by Cupax3** [comment]
> > Apart from this failing checks, do you have an alternative way for players to reach lore information?
> 
> We can always put it on the OOC verbs AND lobby, just like TGMC does.

Please prepare that feature as another PR. No point in fixing a problem only to create a new one for later which is this easy to address right away.

**Comment by Cupax3** [comment]
Testmerge approved as this still leaves a period in the commit history where the Lore button would not be accessible if merged in its current state.

**Comment by EgorDinamit** [comment]
> Testmerge approved as this still leaves a period in the commit history where the Lore button would not be accessible if merged in its current state.

Lore button is now an OOC verb, PR has been updated already.

**Comment by Cupax3** [comment]
> > Testmerge approved as this still leaves a period in the commit history where the Lore button would not be accessible if merged in its current state.
> 
> Lore button is now an OOC verb, PR has been updated already.

Very well.

**Review by Cupax3 — APPROVED** [review]
LGTM

**Pull request merged**
