### PR TITLE
Adds authorship to the PR template

### PR DESCRIPTION
**Pull request by Cupax3**
It's late but whatevs

## About the Pull Request
Adds an authorship section to the default PR template because attribution is nice.

## Why It's Good For The Game
Yes

## Did you test it?
N/A

### CODE REVIEW

**Review by Shadowtail117 — COMMENTED** [review]
If you want to go the extra mile, putting a template `AUTHOR NAMES HERE` on the changelog will help too.

**Comment by Cupax3** [comment]
How can this fail tests?!

**Review by Shadowtail117 — APPROVED** [review]
No extra mile >:(

**Comment by EgorDinamit** [comment]
I don't feel like it's **needed**, but whatever, it's not hard to delete text from PR anyway if it's not a port.

**Pull request merged**
