### PR TITLE
You now trip over catwalks if you're wearing heels

### LINKED ISSUE #36: You don't fall when walking on a catwalk in high heels.
#### Description of issue

You don't fall when walking on a catwalk in high heels.

#### Difference between expected and actual behavior

You don't fall when walking on a catwalk in high heels.

#### Steps to reproduce

1. Wear high heels.
2. Step on the catwalk.
3. Anger.

#### Specific information for locating

Catwalk.

#### Length of time in which bug has been known to occur

For eternity

#### Client version, Server revision & Game ID

Everything.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

### PR DESCRIPTION
**Pull request by Shadowtail117**
## About the Pull Request

Title says it all. If you're wearing high heels and walk over a catwalk, you have a 10% chance to trip and fall, weakening you and bruising you a bit.

Closes #36

## Why It's Good For The Game

High heels are a crime

## Did you test it?

Yes, it works as advertised.

## Changelog

:cl:
tweak: You now have a chance to trip over a catwalk if you're wearing high heels.
/:cl:

### CODE REVIEW

**Comment by Samuuu3** [comment]
I dunno about this one chief

**Review by Cupax3 — COMMENTED** [review]
Do you have an estimate what the performance overhead for this is going to be? It's a check on every movement, including two subprocs you're calling for checks, after all.

**Comment by Cupax3** [comment]
I've taken a cursory glance, if you are serious about this PR I recommend looking into making this part of /obj/structure/catwalk/Crossed(), which should be faaaaaar more performance friendly since it won't query every single movement for checks that don't apply anyways.
For reference, check how banana peels work.

For your convenience: `\code\game\objects\items\weapons\clown_items.dm`

**Comment by Shadowtail117** [comment]
I was half-serious in making this PR, as I assume Egor was half-serious in opening the issue, but I am more than happy to address those changes as well as throw in a few more suggestions people had when I have the time.

**Comment by Shadowtail117** [comment]
Ready for ~~cursed~~ review.

**Comment by Ilysen** [comment]
I'm still not very sure what value this feature holds for the game. The OP's section on this gives no reasoning. What purpose does this serve, except to annoy people who choose to wear high heels? I've seen a nonzero number of people wearing them, at least on bay. Should they be penalized because they use a certain shoe option that's available to them? Why?

It may make more sense from a "realism" standpoint, but realism holds no intrinsic merit. This tweak doesn't increase immersion or believability - it just frustrates a tiny fraction of players for no real net gain anywhere else. My vote is definitely a no, here, unless you have some good reasons for why this feature is a good thing.

**Comment by Shadowtail117** [comment]
Egor gets what egor wants. #36. FWIW I have no intrinsic drive to merge it, just to decrease the open issue count. Edit: also see above comment about half-seriousness.

**Comment by Ilysen** [comment]
Going to defer to @Cupax3 here. I'm almost completely certain that the issue was made as a meme. This PR is definitely not a healthy way of addressing a meme issue compared to just having it closed.

**Comment by Samuuu3** [comment]
I'm also pretty sure Egor was memeing and I don't like this PR personally either

**Comment by Cupax3** [comment]
Closing - issue no longer relevant, apologies for the work invested.

**Pull request closed without merging**
