### PR TITLE
Biomods for more subspecies

### PR DESCRIPTION
**Pull request by SkyCinnamon**
## About the Pull Request

All species aside from Mules can have biomods

## Why It's Good For The Game

From what I understand anyways this is a common sentiment from many vat human players aswell as subspecies in general, they wish they could have biomods. With little reason given as to why they arent allowed I dont see the point in restricting it. To double check this lorewise I had asked Rowtree and they said it would be fine as long as I exclude mules. 

## Did you test it?
Hell yeah brother!
image

## Changelog

:cl: Sky
tweak: All human subspecies aside from mules can have biomods
/:cl:

### CODE REVIEW

**Comment by tiramisuapimancer** [comment]
What about the other human subspecies?

**Comment by SkyCinnamon** [comment]
> What about the other human subspecies?

I dont see why they cant either, for now however I rarely see anyone play any other human subspecies and havent ever seen those players ask for biomods. If you have any specific ones youd like to have them let me know. Vatties were just the only one I asked about.

**Comment by tiramisuapimancer** [comment]
I always thought it'd be cool to play a Tritonian with cat ears, it just seems unfair to leave the rest out on this too

**Comment by SkyCinnamon** [comment]
> I always thought it'd be cool to play a Tritonian with cat ears, it just seems unfair to leave the rest out on this too

done

**Review by Cupax3 — APPROVED** [review]
LGTM

**Pull request merged**
