### PR TITLE
Adds straight identity pins and renames all pride pins

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

Ports Baystation12/Baystation12/pull/29900
Changes name and description of all "pride pins" to be "identity pins".

## Why It's Good For The Game

Inclusivity cannot be exclusive. We either have it all, or we have none.
An alternative to this PR could be the complete removal of all pride pins.

## Did you test it?

A very minor tweak. I do not see a reason to launch up a local server for this.

## Changelog

:cl:
tweak: Straight identity pins were added to the list of identity pins.
tweak: All pride pins were renamed to identity pins.
/:cl:

### CODE REVIEW

**Comment by Shadowtail117** [comment]
**For the purpose of playing devil's advocate**, I will point out that a [a similar pull request](https://github.com/Baystation12/Baystation12/pull/29900) was opened on upstream and closed due to apparent negative connotations on what straight pride is in real life, as heterosexuality is considered the prevalent/dominant sexuality and having "straight pride" could diminish minority sexuality groups.

**Comment by EgorDinamit** [comment]
I know it fairly well, Shadow, but their argument for closing the pull request is rather bland.
As I said in our PR's body - inclusivity can't be exclusive.

**Comment by Cupax3** [comment]
> **For the purpose of playing devil's advocate**, I will point out that a [a similar pull request](https://github.com/Baystation12/Baystation12/pull/29900) was opened on upstream and closed due to apparent negative connotations on what straight pride is in real life, as heterosexuality is considered the prevalent/dominant sexuality and having "straight pride" could diminish minority sexuality groups.

It is acceptable.
As a sorta-precedent-but-it's-situational: Negative connotations only go as far as a person is willing to attribute to them. If people attach negative actions to something like a sexuality pin, I trust the admins will step in and bwoink 'em.

**Comment by triplezeta** [comment]
you people


if you actually care about inclusivity add an ally flag pin

its essentially a way of saying "i support the lgbtq+ movement but dont fall into any group in particular" and doesnt have the homophobic connotations of unironically adding a straight pride pin

**Comment by Cupax3** [comment]
> you people
> 
> 
> if you actually care about inclusivity add an ally flag pin
> 
> its essentially a way of saying "i support the lgbtq+ movement but dont fall into any group in particular" and doesnt have the homophobic connotations of unironically adding a straight pride pin

Anyone is free to add additional content to the codebase. I've chosen equality over equity in this case, thus it's all or nothing. Unless there is a case where content would be illegal, it's a situation where everyone is given their share.

While I recognize that some people have a bad association with straight pride as a moniker - I'd rather prefer the term pride be removed from all the pins, honestly. Just sounds weird - as mentioned above everyone gets to celebrate their own preferences. Inclusivity isn't "pick-your-preference" but being open and accepting of all ideas that aren't infringing on your own personal freedom.

If you have a suggestion for amended wording that could remove the volatility while keeping the spirit of fondness for ones sexuality, please provide it via a comment.

Sincerely,
The homosexual headcoder

**Comment by HighPrincessErinys** [comment]
> If you have a suggestion for amended wording that could remove the volatility while keeping the spirit of fondness for ones sexuality, please provide it via a comment.
> 
> Sincerely, The homosexual headcoder

https://lgbta.wikia.org/wiki/Allies

Parading yourself as "the homosexual headcoder" doesn't change the fact that making a literal "straight pride" pin is outright enabling homophobia. Straight Pride's "bad associations" are very real and very much used to lessen the voice of LGBT people. While not everyone says it with malice it's pretty much equivalent to pushing for a white history month because of black history month, and could on it's own be considered a dogwhistle.

**Comment by Shadowtail117** [comment]
> > If you have a suggestion for amended wording that could remove the volatility while keeping the spirit of fondness for ones sexuality, please provide it via a comment.
> > Sincerely, The homosexual headcoder
> 
> https://lgbta.wikia.org/wiki/Allies
> 
> Parading yourself as "the homosexual headcoder" doesn't change the fact that making a literal "straight pride" pin is outright enabling homophobia. Straight Pride's "bad associations" are very real and very much used to lessen the voice of LGBT people. While not everyone says it with malice it's pretty much equivalent to pushing for a white history month because of black history month, and could on it's own be considered a dogwhistle.

White history month is its own topic with plenty of arguments for and against; however, at face value, "inclusivity cannot be exclusive" is the general idea behind this PR and straight pride -- while, unfortunately, used by bad actors to further an agenda of being anti-LGBT -- is a perfectly valid pride to have.

All of this being said, the comments of this PR are not the best place to be having this discussion. Feel free to join the Discord server and continue it there.

**Comment by EgorDinamit** [comment]
> Parading yourself as "the homosexual headcoder" doesn't change the fact that making a literal "straight pride" pin is outright enabling homophobia. Straight Pride's "bad associations" are very real and very much used to lessen the voice of LGBT people. While not everyone says it with malice it's pretty much equivalent to pushing for a white history month because of black history month, and could on it's own be considered a dogwhistle.

If "gay pride" isn't enabling "heterophobia", then why would "straight pride" enable "homophobia" simply by existing?
LGBT Pride doesn't have fewer bad associations, but we assume those are just bad actors and acknowledge it as it is meant to be, not how some people make it out to be.

If you really care about this topic - we'd like to hear a suggestion on what would replace the word "pride" altogether, for every single pin in the game.

**Comment by Cupax3** [comment]
Hello,

To avoid this turning into a political discussion, please move the talks about the merit of the pins to the Discord.

I'll be marking any other comments not containing constructive feedback, like suggestions, as off-topic.

Thank you.

**Comment by EgorDinamit** [comment]
Alright, changed PR a bit if anyone cares.

**Review by Cupax3 — APPROVED** [review]
LGTM

**Comment by SierraKomodo** [comment]
> 
> 
> **For the purpose of playing devil's advocate**, I will point out that a [a similar pull request](https://github.com/Baystation12/Baystation12/pull/29900) was opened on upstream and closed due to apparent negative connotations on what straight pride is in real life, as heterosexuality is considered the prevalent/dominant sexuality and having "straight pride" could diminish minority sexuality groups.

Just want to clarify the actual reason for closing the PR.

Straight Pride is the name of an anti-LGBTQ movement, similar to 'Blue Lives Matter' is an anti BLM movement. 

https://en.wikipedia.org/wiki/Straight_pride

**Pull request merged**
