### PR TITLE
Recharger tweaks

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

- Rechargers now take capacitors to upgrade the charge rate.
- Machines now have proper info on tool manipulation.

## Why It's Good For The Game

- More and more machines should be able to be upgraded.
- Fixes a bug.

## Did you test it?

Yes, all tested, all good.

## Changelog

:cl:
tweak: Rechargers can now be upgraded with better capacitors to increase the rate at which items are being recharged.
fix: Machines now have proper information on tool manipulation.
/:cl:

### CODE REVIEW

**Comment by Shadowtail117** [comment]
Do rechargers have a sprite for having their panel open?

**Comment by SomeGuy85x2** [comment]
Assuming the panel open icon would be in the same place as the rest of it's sprites, we don't seem to have one. However, tg station does have an icon for that, which seems to line up visually with ours, so that might be worth porting over.

**Comment by EgorDinamit** [comment]
> Do rechargers have a sprite for having their panel open?

They do now.

**Review by Shadowtail117 — APPROVED** [review]
ITYE

**Pull request merged**
