### PR TITLE
Gas capital 

### PR DESCRIPTION
**Pull request by SkyCinnamon**
## About the Pull Request

changes GAS define to be capitalized. SMH

Bay pr did this and thought it was a good idea

## Why It's Good For The Game

You may be asking yourself "why". Over the last 50 years in game lore GAS have had an identity crisis. one which they did not know how to fix. for this my hands were drawn. Am I to resolve the quarrel over whether they are giant armoured serpentid or Giant armoured  serpentid. this will help stow away resentment from our strong and vastly unique GAS playerbase.  What will be next? Find out next time on Sky PR roulette !

## Did you test it?

Hell yeah brother!
image

## Changelog

:cl:
spellcheck: changed capitalization in GAS define
/:cl:

### CODE REVIEW

**Comment by Samuuu3** [comment]
Hey a not hat PR

**Comment by SkyCinnamon** [comment]
> Hey a not hat PR

its okay my next pr will be a hat PR

**Review by Shadowtail117 — APPROVED** [review]

**Comment by Shadowtail117** [comment]
Actually - changelog is not formatted correctly, it should be:
> spellcheck: changed capitalization in GAS define

**Comment by SkyCinnamon** [comment]
> Actually - changelog is not formatted correctly, it should be:
> 
> > spellcheck: changed capitalization in GAS define

it done will change my other prs

**Comment by Cupax3** [comment]
@Samuuu3 Species Maintainer goes lore reviewwwwww

**Review by Samuuu3 — APPROVED** [review]
It looks better than all lower case

**Pull request merged**
