### PR TITLE
Replaces most show_browser instances with browser popups

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

Almost every show_browser instance is replaced with a better-looking popup.

Also fixes some stuff here and there, like UI not updating in some objects during actions.

## Why It's Good For The Game

No more ugly white-background stupid UI. Everything looks better now.

UIs now update properly and don't look bad.

## Did you test it?

I tested it, I spawned pretty much every single object and item that has been updated.
It works as expected, but I'd imagine test-merge wouldn't hurt.

## Changelog

:cl:
tweak: A lot of old browsers UIs are replaced with better-looking browser popups.
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
Has this been tested for the more extensive machine interfaces that update fairly regularly?

**Comment by Shadowtail117** [comment]
This has been testmerged for a while, have there been any major problems?

**Comment by Cupax3** [comment]
@EgorDinamit see above by Shadow.

**Comment by EgorDinamit** [comment]
> This has been testmerged for a while, have there been any major problems?

Nothing. All issues were fixed at some point in this PR's life.

**Review by Cupax3 — APPROVED** [review]
LGTM by trial of scream test

**Pull request merged**
