### PR TITLE
Unathi can wear head of staff HCMs

### LINKED ISSUE #22: Head of staff hardsuits do not fit Unathi
#### Description of issue

The head of staff hardsuits available in the auxiliary EVA storage do not fit unathi because of their digitigrade legs, and are thus unwearable. It is possible this also extends to skrell.

#### Difference between expected and actual behavior

Given that unathi can be heads of staff now, it makes sense that they can wear the hardsuits intended for them.

#### Steps to reproduce

Self-explanatory.

#### Specific information for locating

Likely the issue that the boots are not designed for digitigrade feet. The medical EVA hardsuit works for plantigrade and digitigrade, and the appropriate behavior can likely be taken from there.

#### Length of time in which bug has been known to occur

Probably forever, but only became an issue after #12.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: Revision Unknown
Game ID: ccB-de4c
Current map: SEV Torch

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

### PR DESCRIPTION
**Pull request by Shadowtail117**
## About the Pull Request

Allows unathi to wear head of staff HCMs.

See the comment below for what the new sprites look like from a head-on perspective. Download the .dmis to see all of them.

he feet too big for he goddamn he
## Why It's Good For The Game

Unathi can be heads of staff, so they should be able to wear the hardsuits designated for them.

## Did you test it?

Yes on the mechanical change. ~~Sprites have yet to be introduced.~~

## Changelog

:cl:
tweak: Unathi can now wear command HCMs. Rejoice.
/:cl:

### CODE REVIEW

**Comment by Shadowtail117** [comment]
PR has been updated with my own coder sprites, largely based off of both unathi ERT and EVA hardsuit sprites. Quality not guaranteed, but they are better than nothing. **These sprites do not have a tail model**
image
image
image
image
image

**Comment by Shadowtail117** [comment]
Also now that these have sprites that are at least *passable*, this is no longer a draft

**Comment by Shadowtail117** [comment]
squoomshed

**Review by EgorDinamit — APPROVED** [review]
Should be good to go.

**Pull request merged**
