### PR TITLE
Removes a lot of posters, adds 2 new ones and implement unused posters

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

- Adds 2 new posters that were made on /tg/ TeguStation previously by me.
- Removes A LOT of Bay posters, including all of the pinup posters and those that were simply downscaled images.
- Changes poster code a tiny bit to allow for random posters by type.

## Why It's Good For The Game

- Some of the old stuff + lore.
- Seriously, a lot of those posters were VERY low quality and all the "pinup" posters were borderline erotic content. You may not care about it, but idk why would we need it here.
- Just a little "refactor" to make it less hard-coded..? Might be useful in the future.

## Did you test it?

I did, it all works as expected.

## Changelog

:cl:
rscadd: 2 new posters added.
rscdel: A lot of Bay posters were deleted, mainly low-quality ones.
/:cl:

### CODE REVIEW

**Comment by Cupax3** [comment]
I'd like to know why some of the more harmless references are included in the removals?

**Comment by EgorDinamit** [comment]
The "more harmless" ones were mostly low-quality images, stretched from their original size to 32x32.
Only those that don't look terrible in-game will remain.

**Comment by Cupax3** [comment]
Is there any specific inspiration behind tposter11s sprite?

**Comment by EgorDinamit** [comment]
> Is there any specific inspiration behind tposter11s sprite?

It was a poster I made for ISC - Independent Space Confederation that was basically an alliance of several governments/groups that fought against the Terran Government.
Here it's just a vague symbol of unity unless we re-implement ISC in some way.

**Review by Cupax3 — APPROVED** [review]
LGTM

**Pull request merged**
