### PR TITLE
Changeling code refactor + accommodating balance adjustments

### PR DESCRIPTION
**Pull request by Ilysen**
## About the Pull Request

This PR body is largely taken from my initial PR on bay, at Baystation12/Baystation12/pull/30815.

<details><summary>How does this affect me as a player?</summary>

I recommend you check the Media section for a visual aid to this list!
* Changeling powers are now used via action buttons in a collapsible category. Chemical display is still in the Status panel.
* Turning into a monkey via Lesser Form is a bit faster, putting it in sync with the animation.
* Regenerative Stasis will send you a message even if you're ghosted when you're ready to use it.
* You see a link to the Codex when becoming a changeling that you can click for more info about them.
* Absorbing (or being absorbed) now has spooky text associated with it. Bonus points if it's changeling on changeling!
* Rewrote most of, if not all, of the text shown by changeling abilities.
</details>

<details><summary>Backend updates</summary>

* removed pretty much all of the `/mob` procs used for changeling abilities.
* migrated all changeling abilities onto `/datum/power`, which actually existed in the first place for changeling abilities but was only used to give verbs for some reason. added a `/changeling` subtype to it, and a bunch of abstract functions to make them more useful.
* moved a bunch of changeling-related `/mob` procs not used for abilities onto the changeling datum (`/datum/changeling`) instead.
* changeling abilities now use the ability manager system to display icons in a way similar to wizard spells, because they're no longer verbs. (if it's desired, I could use `statpanel` calls to make the buttons clickable in a status panel, though)
* cleaned up many variable names, function calls, and documentation.
* the changeling datum is now housed in `changeling_datum.dm`
* some ling-related helper functions are now found in `changeling_helpers.dm`
* all changeling powers are now in `changeling_powers.dm`
* `modular_changeling.dm` has been removed and split amongst these three files
* commented every field in the changeling datum in accordance with spacemandmm documentation standards

Sprite assets for the spells were either reused from existing assets or kitbashed by myself. some ability icon variables have a comment saying `// {PH}` next to them, which means it's technically placeholder until it gets a dedicated asset, but it fits well enough to not be a big deal.
</details>

<details><summary>Relevant balance adjustments</summary>

* Turning into a monkey from a human takes 2.5 seconds instead of 4.8.
* You now receive a message if you try to talk while silenced.
* Medical HUDs are fooled by changeling stasis, zombie powder, and other sources of fake death.
</details>

All feedback on code is totally welcomed.

## Why It's Good For The Game

Changeling code is very entangled and very old. It has quite a few bugs, and its interface suffers from needing to rely on BYOND verbs to function. Much of these bugs are caused by a lack of modularity and modernization. This PR endeavors to refresh both the backend and the player experience for changeling. The interface should make playing changeling much more intuitive than it currently is.

<details><summary>Rationale for balance changes:</summary>

* in polishing ling, I also wanted to polish the most common source of silencing. I have personally fallen victim to asking in LOOC why I can't talk, and having a message makes it explicit that not being able to talk is intended and not a bug. I'm not glued to this, so if it needs to be removed, that's fine.
* lesser form showed that you'd stay locked in place with nothing happening for almost a full two seconds. reducing it makes it feel much more responsive to what the sprites actually show!
* I think it's intended for fakedeath to convince medical devices, so I extended that to the medical HUD.
</details>

## Did you test it?

Tested very extensively back when I was first writing the code. I rebased the branch onto Tegu's `dev` branch in the process of porting my work here, made myself a changeling through admin commands, and ran around the Torch getting myself killed to test the stasis as well as murdering test dummies to test absorption, and so on. My testing on Tegu has not been as extensive as my testing on Bay - I recommend a testmerge or local validation before merge here.

## Media

<details><summary>Default abilities. From right to left: Evolution Menu, Absorb DNA, Transform, Regenerative Stasis, Hive Channel, Hive Absorb</summary>

image
</details>

<details><summary>A bunch of stings unlocked: Deaf, Blind, Mute, DNA, Hallucination, and Death, plus Boost Range</summary>

image
</details>

<details><summary>Collapsing the interface to hide all the buttons</summary>

image
</details>

<details><summary>Some abilities that are active - Digital Camouflage and Boost Range. You can also see the shadow effect that displays when abilities don't have the sufficient chems to activate.</summary>

image
</details>

<details><summary>Putting it all together</summary>

image
</details>

## Future Goals?

1. On-screen chemical display in some form.
2. Further improvements to feedback.
3. Change evolution menu into a proper ability/function instead of a verb.
4. If possible, make stasis display how long you have to wait.

## Changelog

🆑
rscadd: Revamped the way changeling abilities are shown. Instead of existing in a verb tab, they now have buttons like spells. Actual functionality should remain (mostly) unchanged.
tweak: Changeling stasis will now send a message and sound to the user if they're dead and have ghosted, allowing them to know when to return to their body.
tweak: Rewrote the messages for a bunch of changeling abilities.
tweak: Improved the user feedback for some changeling abilities.
tweak: Changeling stasis and other fake death sources are now more convincing. Examine texts, medical scanners, medical HUDs, and other sources are now fooled by fake death, and fake-dead mobs will no longer gasp or make other emotes.
balance: You will now receive a message if you fail to speak while silenced, instead of it failing with no feedback.
balance: Monkeyizing is a little faster.
balance: Medical HUDs will now detect changelings in stasis as being dead, rather than alive.
balance: Because the AI role doesn't currently exist, Digital Camouflage has been made free to purchase and maintain, as it is primary a roleplay ability now.
/🆑

### CODE REVIEW

**Review by Cupax3 — DISMISSED** [review]
Tentatively LGTM, testmerge skipped for scream test instead.

**Comment by Ilysen** [comment]
Will need to resolve conflicts because of the globals update, one moment

**Comment by Cupax3** [comment]
On second viewing, it merge conflicts with #59 - plox rehash the globals

**Comment by Cupax3** [comment]
Merge conflict dodododoooo

**Review by Cupax3 — APPROVED** [review]
Apologies for lateness, LTGM - scream test stands.

**Pull request merged**
